### ISSUE TITLE
服务端启动崩溃

### ISSUE THREAD

**Issue by ChromaPIE** [TartaricAcid/NetMusic#1]
[latest.log](https://github.com/TartaricAcid/NetMusic/files/7814749/latest.log)

**Comment by Kamijouko** [comment]
同上，查出是netMusic与CraftTweaker冲突
`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 22-1-30 上午1:30
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at com.github.tartaricacid.netmusic.client.config.MusicListManage.<clinit>(MusicListManage.java:24)
	at com.github.tartaricacid.netmusic.item.ItemMusicCD.func_150895_a(ItemMusicCD.java:59)
	at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:53)
	at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:63)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_84_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 17 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@10b3df93 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 19 more
Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2022 (amd64) version 10.0
	Java Version: 1.8.0_321, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 31708684728 bytes (30239 MB) / 32142524416 bytes (30653 MB) up to 32142524416 bytes (30653 MB)
	JVM Flags: 6 total; -Xincgc -XX:MetaspaceSize=10G -XX:MinMetaspaceFreeRatio=20 -XX:MaxMetaspaceFreeRatio=40 -Xmx30G -Xms30G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version      | Source                                  | Signature                                |
	|:----- |:--------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2       | minecraft.jar                           | None                                     |
	| LCH   | mcp             | 9.42         | minecraft.jar                           | None                                     |
	| LCH   | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge           | 14.23.5.2860 | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | crafttweaker    | 4.1.20       | 77.CraftTweaker2-1.12-4.1.20.673.jar    | None                                     |
	| LCH   | crafttweakerjei | 2.0.3        | 77.CraftTweaker2-1.12-4.1.20.673.jar    | None                                     |
	| LCH   | netmusic        | 1.0.1        | 88.netmusic-1.12.2-1.0.1.jar            | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by MikhailTapio** [comment]
> 同上，查出是netMusic与CraftTweaker冲突 服务端为spongeForge端 客户端启动没问题
> 
> ```
> ---- Minecraft Crash Report ----
> // Uh... Did I do that?
> 
> Time: 22-1-30 上午1:30
> Description: Exception in server tick loop
> 
> java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
> 	at com.github.tartaricacid.netmusic.client.config.MusicListManage.<clinit>(MusicListManage.java:24)
> 	at com.github.tartaricacid.netmusic.item.ItemMusicCD.func_150895_a(ItemMusicCD.java:59)
> 	at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:53)
> 	at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:63)
> 	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:60)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_84_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
> 	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
> 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
> 	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
> 	at java.lang.Thread.run(Thread.java:750)
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 17 more
> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@10b3df93 from coremod FMLCorePlugin
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
> 	... 19 more
> Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
> 	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
> 	... 21 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows Server 2022 (amd64) version 10.0
> 	Java Version: 1.8.0_321, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 31708684728 bytes (30239 MB) / 32142524416 bytes (30653 MB) up to 32142524416 bytes (30653 MB)
> 	JVM Flags: 6 total; -Xincgc -XX:MetaspaceSize=10G -XX:MinMetaspaceFreeRatio=20 -XX:MaxMetaspaceFreeRatio=40 -Xmx30G -Xms30G
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State | ID              | Version      | Source                                  | Signature                                |
> 	|:----- |:--------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
> 	| LCH   | minecraft       | 1.12.2       | minecraft.jar                           | None                                     |
> 	| LCH   | mcp             | 9.42         | minecraft.jar                           | None                                     |
> 	| LCH   | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCH   | forge           | 14.23.5.2860 | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCH   | crafttweaker    | 4.1.20       | 77.CraftTweaker2-1.12-4.1.20.673.jar    | None                                     |
> 	| LCH   | crafttweakerjei | 2.0.3        | 77.CraftTweaker2-1.12-4.1.20.673.jar    | None                                     |
> 	| LCH   | netmusic        | 1.0.1        | 88.netmusic-1.12.2-1.0.1.jar            | None                                     |
> 
> 	Loaded coremods (and transformers): 
> 	Profiler Position: N/A (disabled)
> 	Is Modded: Definitely; Server brand changed to 'fml,forge'
> 	Type: Dedicated Server (map_server.txt)
> ```

其实和CRT关系不大，就是一个在服务端调用客户端类的错误。

**Comment by TartaricAcid** [comment]
了解，今天这个项目又重启了，可以开工复活了

**Comment by TartaricAcid** [comment]
https://www.mcmod.cn/download/4935.html
