### ISSUE TITLE
添加绕过系统代理的客户端配置

### ISSUE THREAD

**Issue by PopSlime** [TartaricAcid/NetMusic#14]
## 动机
Java 的 HTTP API 与部分代理不兼容，即便这些代理工作正常，Java 的 HTTP API 也会连接超时。

## 描述
添加一个“绕过系统代理”的客户端配置。当其启用时，在所有对 `urlConnect.openConnection()` 引用中传入 `Proxy.NO_PROXY` 参数。

## 参考
- [`java.net.URL.openConnection(java.net.Proxy)`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/net/URL.html#openConnection(java.net.Proxy))
- [`java.net.Proxy.NO_PROXY`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/net/Proxy.html#NO_PROXY)

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/NetMusic/commit/8c477de427c8204e5e8d7f642a5800cbf3cd4016

已完成
