### ISSUE TITLE
多人游戏下，中途进入唱片机范围的玩家无法听到音乐

### ISSUE THREAD

**Issue by TowardtheStars** [TartaricAcid/NetMusic#15]
## 问题描述
多人游戏下，唱片机开始播放后再进入唱片机范围的玩家无法听到音乐，只有重新放置唱片之后才能使其听到音乐

## 复现步骤
1. 纯 Forge 服务端启动服务器
2. 两个玩家进入服务器
3. 玩家 1 离开唱片机范围
4. 玩家 2 播放音乐，音乐可以被玩家 2 听到
5. 玩家 1 回到唱片机范围，发现玩家 1 听不到音乐
6. 重新放置唱片，玩家 1 和玩家 2 均可听到音乐

影响到的版本
------------------------
Minecraft: 1.20.1
Forge: 47.2.17
NetMusic: netmusic-1.20-1.1.1.jar

**Comment by TartaricAcid** [comment]
无法解决，原版唱片也有这问题
