### ISSUE TITLE
Youtube Support plz.

### ISSUE THREAD

**Issue by ItsukaHiro** [TartaricAcid/NetMusic#17]

**Comment by TartaricAcid** [comment]
## YouTube
1. find you music youtube url link, I gave you some example : `https://www.youtube.com/watch?v=UqP8rZu6xLM`

![1](https://cdn.modrinth.com/data/cached_images/169b2dbf64cd2c2dba9983f621c6bae9602c62c6.png)  
2. now paste your link at yt2mp3 converter: [https://mp3-convert.org/youtube-to-mp3-converterss/](https://mp3-convert.org/youtube-to-mp3-converterss/)

![2](https://cdn.modrinth.com/data/cached_images/fb717d6ab5de4475afeda92658abc3a4bf70b087.png)  
3. convert and you got 2 section download and convert next.

![3](https://cdn.modrinth.com/data/cached_images/2eb43168a2224727cbca4ceccf0e0e48ff0629f3.png)  
4. Right click download section and copy link address

![4](https://cdn.modrinth.com/data/cached_images/aed3a6a34eab7a630bc423981235ab2d72d99e45.png)  
5. input at song url in game, dont forget to input song time

![4](https://cdn.modrinth.com/data/cached_images/55558095b9daefcf31e91eb792fed3990b5d1ed8.png)

**Thanks to Kucing, luckyu19 for the help**
