### ISSUE TITLE
装上就启动不了了，感觉是mod冲突或者没装前置

### ISSUE THREAD

**Issue by BKAzrae** [TartaricAcid/NetMusic#6]
[latest.log](https://github.com/TartaricAcid/NetMusic/files/12310615/latest.log)
[crash-2023-08-10_16.17.15-fml.txt](https://github.com/TartaricAcid/NetMusic/files/12310622/crash-2023-08-10_16.17.15-fml.txt)

**Comment by TartaricAcid** [comment]
问题非常奇怪，说是我的某个字段没有，但是明明写的好好地啊，请你那边删减一下模组，看看是不是别的模组导致的……

**Comment by TartaricAcid** [comment]
已修复，请重新下载
